import = ["~/.config/alacritty/cyberdream.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.5
normal = { family = "JetBrains Mono Nerd Font Mono", style = "Medium" }
bold = { family = "JetBrains Mono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font Mono", style = "Bold Italic" }

[window]
dynamic_title = true

[window.padding]
x = 5
y = 5
